project:
  type: manuscript
  output-dir: docs

manuscript:
  article: index.qmd

format:
  html:
    comments:
      hypothesis: true
  docx: default
  pdf: default

execute:
  freeze: true

editor: visual

title: Klippel-Trenaunay Syndrome complicated by Kasabach-Merritt syndrome during pregnancy
subtitle: A case report and review of the literature

bibliography: references.bib
csl: vancouver.csl

