# Authors

Mourad Elfaham^1^, Aya Attia^1^, Mohamed Waheed^1^, Mohamed Essam^1^, Salma Saad^1^, Mariam Sarhan^1^, Marwa Mourad^1^, Mohamed Hegazy^1^, Farah Said^1^, Sarah Tarek^1^, Amgad Gamal^1^, Sara Ibrahim Abdelkader^2\*^, Ahmed Azab^2^, Mohammed Ghanem^2^, Rahma Alaa Abdelhafez^2^, Nour Atif^2^, Maha Moemen^2^, Belgin Ahmed Nagah^2^, Ashraf Nabhan^1,3^

# Affiliation

^1^ Faculty of Medicine, Ain Shams University, Cairo, Egypt.

^2^ Faculty of Medicine, Galala University, Attaka, Suez, Egypt.

^3^ Faculty of Medicine, MTI University, Cairo, Egypt. 01069663999

\* Corresponding author: Sara Ibrahim Abdelkader. Faculty of Medicine, Galala University, Attaka, Suez, Egypt. Email: [sara.elzeftawy\@gu.edu.eg](mailto:sara.elzeftawy@gu.edu.eg), ORCID: [0009-0002-5877-4722](https://orcid.org/0009-0002-5877-4722)

**Word count:** 2500

# Abstract

The co-occurrence of Klippel–Trenaunay syndrome and Kasabach-Merritt syndrome in pregnancy is extremely rare and represents a critical obstetric emergency with significant maternal and fetal risks, demanding early recognition and immediate multidisciplinary intervention.

We report the case of a 28-year-old pregnant woman with known Klippel–Trenaunay syndrome who developed Kasabach–Merritt phenomenon during pregnancy. The fetus suffered severe growth restriction and absent end-diastolic flow on umbilical artery Doppler. A cesarean section was performed at 35 weeks of gestation.

This case highlights the complexity of managing pregnancy in women with Klippel–Trenaunay syndrome complicated by Kasabach Merritt syndrome and emphasizes the importance of multidisciplinary surveillance and timely delivery.

**Keywords:** Klippel–Trenaunay syndrome; angioosteohypertrophy syndrome; Kasabach Merritt syndrome; fetal growth restriction; high-risk pregnancy

# Introduction

Klippel-Trenaunay syndrome (KTS) is a rare congenital disorder affecting an estimated 2–5 per 100,000 individuals. Its features include a triad of capillary malformations, venous and lymphatic anomalies, and limb overgrowth. [@ISSVA2018; @Pavone2023]

KTS was first described in 1900 as Naevus vasculosus osteohypertrophicus by two French physicians, Maurice Klippel and Paul Trenaunay. It was previously considered similar to the less common Parkes Weber syndrome (PWS), which is distinguished from KTS by the presence of arteriovenous malformations (AVMs) in the affected limb, which is abnormal connections between arteries and veins in the affected limb, potenially leading to high-output heart faliure. Despite this distinction, both conditions share similar management principles.[@mckusick1963; @sikova1999]. KTS is currently classified within the PIK3CA-Related Overgrowth Spectrum (PROS), a group of overgrowth syndromes with overlapping phenotypic features that share mutations in the PIK3CA gene.

When pregnancy occurs in the setting of KTS, it presents significant challenges due to hormonally and hemodynamically driven vascular engorgement, increasing the risk of thromboembolism, hemorrhage, and coagulopathy. [@Blei2024] Coagulopathy may reflect the development of Kasabach-Merritt syndrome (KMS).

Even more rarely, Kasabach-Merritt Syndrome (KMS), first described in 1940, is a life-threatening consumptive coagulopathy associated with rapidly proliferating vascular tumors such as kaposiform hemangioendothelioma and tufted angioma, and can emerge or worsen during pregnancy in women with KTS. KMS in pregnancy is exceedingly rare, but when it occurs, it carries a historical mortality rate of 30–40%, driven by severe thrombocytopenia, hypofibrinogenemia, and disseminated intravascular coagulation (DIC). [@Tian2026]

The co-occurrence of KTS and KMS in pregnancy represents a critical obstetric emergency, that demands early recognition and immediate multidisciplinary intervention to reduce mortality. This convergence is extremely rare and only three cases have been previously reported.[@Neubert1995; @Kanmani2021; @zhang2019].

This case report details the clinical course and successful management of a pregnant woman with KTS complicated by acute KMS and fetal growth restriction with abnormal umbilical artery Doppler findings. We highlight the clinical challenges and management strategies and underscores the importance of early recognition and coordinated care to optimize maternal and neonatal outcomes.

# Case Presentation

A 28-year-old multigravida, P2CS+1 (1L) was first admitted at 30+1 weeks of gestation for clinically significant hematuria on the 16th of December in Ain Shams University Hospital, Egypt. The timeline is detailed in @tbl-1

The patient was first diagnosed at two years of age with Klippel-Trenaunay syndrome (KTS) involving both lower limbs, back, pelvis, and urinary bladder. She underwent surgery for varicose veins seven years ago, as well as orthopedic surgery for the insertion of plates and screws a year and a half ago.

Her obstetric history includes two cesarean sections. Her first pregnancy was seven years ago and ended in neonatal death. Her second pregnancy was complicated by severe preeclampsia, postpartum wound hematoma, and sepsis, requiring ICU admission. She also had a history of spontaneous miscarriage for which she did not undergo dilatation and curettage. For her current pregnancy, she received two doses of antenatal corticosteroids on December 14^th^ and 15^th^.

On examination, her blood pressure was 120/80 mmHg, temperature was 36.2° C, and heart rate was 68 bpm. Port-wine stains were seen in the back and gluteal region with discrepancy in the length of both lower limbs.

A complete blood picture (CBC) revealed microcytic hypochromic anemia (hemoglobin 7.0 g/dl, hematocrit 23.0%) and thrombocytopenia (128,000 u/L), for which she received six units of packed cell transfusion to correct the worsening hemoglobin. ABO and Rh typing indicated B positive blood. Viral workup was negative for Hepatitis C and B and human immunodeficiency virus (HIV).

Ultrasonography (US) demonstrated estimated fetal weight below the 10th percentile consistent with intrauterine growth restriction (IUGR), and an abnormal umbilical artery Doppler showing absent end-diastolic blood flow.

Urological consultation was sought for the significant hematuria. Initial management included intravenous tranexamic acid and insertion of an indwelling silicone three-way urinary catheter for one week.

On December 18^th^, pelviabdominal magnetic resonance imaging (MRI) was performed, demonstrating a gravid uterus with a single intrauterine pregnancy in cephalic lie with unremarkable placental location and attachment. Compression of the left ovarian vein and the left common iliac vein by the gravid uterus was seen, with associated slowing and dilatation of both veins. Extensive dilated tubular tortuous lesions suggestive of varicosities were observed in the pelvic, perivesical, perineal, and gluteal regions, more prominent on the left side, showing a “bag of worms” appearance. Similar lesions were present in breast subcutaneous tissue bilaterally. The urinary bladder contained blood products.\
The liver was mildly enlarged with noticeable vascular compression, while the gall bladder, spleen, and kidneys were unremarkable. Minimal bilateral pleural effusion was noticed.

On December 21^st^, pelviabdominal ultrasonography, Color-Doppler study of both lower limb veins, and Color-Doppler and duplex study of both lower limb arteries were performed.\
Pelviabdominal ultrasonography revealed hepatosplenomegaly, soft tissue lesions in the urinary bladder, bilateral refluxing parametrial venous channels, and a single viable intra-uterine fetus.\
Lower limb vessel studies showed a normal venous and arterial system, with no evidence of deep vein thrombosis.

Serial CBCs showed improving hemoglobin over the four days following the packed RBCs transfusion, which reached 9.4g/dL on December 22^nd^, while platelet count remained persistently low between 82,000 and 104,000. Iron profile showed elevated UIBC (unsaturated iron binding capacity) and low transferrin saturation. Lactate dehydrogenase (LDH) was elevated at 454 IU/L.\
On the same day, urinalysis demonstrated hematuria (2+), pyuria, and mild proteinuria (1+). Microscopic examination revealed \>100 red blood cells per high power field (RBCs/HPF), 40-45 pus cells per high power field (Pus Cell/HPF), and increased epithelial cells (2+). Uric acid crystals were present (2+). Other parameters were within normal limits.

Coagulation studies on December 27^th^ and 28^th^ showed slightly elevated Prothrombin time (PT) while serum creatinine was low.

A contrast-enhanced pelvic MRI was done on January 1, showing extensive venous malformations within the pelvis involving the cervix, vagina, anal canal, and extending downwards to the perineum and both labias. Extensive lesions were also seen within the gluteal region, thigh, anterior part of the abdominal cavity, and intravesically.

The patient was monitored daily with regular assessment of vital parameters, general condition, fetal kicks, vaginal bleeding, uterine contractions, and evidence of membrane rupture. She received one unit of packed RBCs on January 2, followed by an additional unit on January 5.  

At 35 weeks of gestation, based on worsening fetal Doppler parameters and maternal risks, a multidisciplinary team involving obstetrics, hematology, anesthesia, and neonatology recommended delivery by emergency cesarean section. Subsequently, on the 18^th^ of January, a cesarean section was performed at 35 weeks of gestation under general endotracheal anesthesia.\
Vertical midline abdominal incision was made revealing significant varicosities in the anterior abdominal wall, over the lower uterine segment, and in the interface between the uterus and the bladder. Lower segment incision of the uterus was made to deliver the fetus and placenta. This was followed by closure of the uterine wall in two layers. Placenta was complete, perineum intact. Hemostasis was secured and no intraperitoneal drains were left. Only a subcutaneous drain was inserted for seven days. The skin was closed by interrupted mattress sutures.

A female neonate weighing 1900 g was delivered with Apgar scores of 7 and 9 at 1 and 5 minutes respectively. The neonate did not receive vaccination due to low birth weight and did not require observation or respiratory support.

Postoperatively, the mother was admitted to the intensive care unit (ICU) due to hemoperitoneum. Her pharmacological therapy included low-molecular-weight heparin (LMWH), tranexamic acid, ceftriaxone, pantoprazole, intravenous paracetamol, and charcoal-based herbal

Slight hematuria was noted on the first post-operative day, and labs showed a declining hemoglobin and platelet count, as well as markedly elevated LDH, alkaline phosphatase, creatine kinase, and bilirubin. LMWH therapy was thereby put on hold, and the patient was given packed red blood cells and fresh frozen plasma, receiving a total of ten units of packed cell transfusion and fresh frozen plasma (with a one-to-one ratio) over the course of seven days. Additional laboratory investigations are demonstrated in @tbl-2

On the second post-operative day, the patient's hemoglobin and platelet count rapidly deteriorated, decreasing from 9.6g/dl and 218,000 plt to 7.6g/dl and 104,000 plt respectively. Replacement with blood products continued.

On post-operative day three, TVUS revealed marked hemoperitoneum with a localized hematoma related to the lower uterine segment, approximately 12 cm in maximum length. A decision for conservative management was made by the attending consultant and the head of the unit. Pharmacological therapy was adjusted; LWMH was resumed, in addition to tranexamic acid, 1 amp calcium, 1 amp dexamethasone, magnesium sulfate, cefepime, omeprazole, clindamycin, and intravenous paracetamol.

On post-operative day four, labs showed low fibrinogen (1.4g/l) and significantly elevated D-dimer (35.200 ug/mlFEU). These findings were suggestive of Kasabach Meritt Syndrome.

Urinalysis on day 6 demonstrated hematuria (2+), mild pyuria and mild proteinuria (1+). Microscopic examination revealed \>100 red blood cells per high power field (RBCs/HPF), 13-15 pus cells per high power field (Pus Cell/HPF), and increased epithelial cells (1+). On day 7, her hemoglobin stabilized at 10.1 g/dl and remained stable over the following three days, while her platelet count remained low at 64,000.

After further stabilization, the patient was discharged on day ten postoperatively. She was seen on day nineteen in the outpatient clinic. General condition was fair, lax abdomen, and skin sutures were removed with optimal healing of the abdominal incision.

+--------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Date                                 | Timeline                                                                                                                                                                                                                   |
+======================================+============================================================================================================================================================================================================================+
| December 16, 2025                    | Admission of pregnant 28-year-old presenting with hematuria with prior diagnosis of Klippel-Trenaunay Syndrome (KTS). \                                                                                                    |
| (30+1 weeks)                         |                                                                                                                                                                                                                            |
|                                      | CBC revealed anemia and thrombocytopenia; ultrasound demonstrated fetal weight                                                                                                                                             |
|                                      | below 10^th^ percentile.\                                                                                                                                                                                                  |
|                                      |                                                                                                                                                                                                                            |
|                                      | Tranexamic acid and six units of packed red cell transfusion were administered.                                                                                                                                            |
+--------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| December 18, 2025 – January 17, 2026 | MRI showed extensive venous malformations in the pelvis, thigh, and anterior part of the abdominal cavities.                                                                                                               |
|                                      |                                                                                                                                                                                                                            |
|                                      | Regular fetal and maternal monitoring continued, with packed red blood cell transfusions as needed. Hemoglobin slightly improved. Platelet count initially increased before rapidly declining again. PT was prolonged.     |
+--------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| January 18, 2026\                    | Emergency cesarean section due to worsening fetal status. A female neonate weighing 1900g was delivered.\                                                                                                                  |
|                                      |                                                                                                                                                                                                                            |
| (35 weeks of gestation)              | The mother was admitted to the ICU due to hemoperitoneum. LMWH was initiated                                                                                                                                               |
|                                      | along with tranexamic acid and other medications.                                                                                                                                                                          |
+--------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 1st post-op day                      | Hematuria was noted, prompting discontinuation of LMWH.\                                                                                                                                                                   |
|                                      |                                                                                                                                                                                                                            |
|                                      | A total of ten units of red blood cells and fresh frozen plasma were transfused                                                                                                                                            |
|                                      | over the course of the following seven days.                                                                                                                                                                               |
+--------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 2nd post-op day                      | Hemoglobin and platelet count decreased markedly, from 9.6g/dL and 218,000 to 7.6g/dL and 104,000 plt, respectively                                                                                                        |
+--------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 3rd post-op day                      | A decision for conservative management was made. LWMH was resumed, along with tranexamic acid and other medications.                                                                                                       |
+--------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 4th post-op day                      | Laboratory studies showed low fibrinogen (1.4g/l) and high D-dimer (35.2 ug/ml/ FEU), suggesting Kasabach-Meritt Syndrome.                                                                                                 |
+--------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 7th post-op day                      | Hemoglobin stabilized at 10.1g/dl, platelet count remained low at 64,000.                                                                                                                                                  |
+--------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 10th post-op day                     | Patient was discharged                                                                                                                                                                                                     |
+--------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 19th post-op day                     | Follow-up at the outpatient clinic. General condition was fair and abdominal sutures were removed.                                                                                                                         |
+--------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

: Patient timeline {#tbl-1}

| Parameters/Timing | December 16 (Day of admission) | December 22 | December 28 | POD 1 | POD 2 | POD 4 | POD 6 | POD 7 | Reference range |
|--------|--------|--------|--------|--------|--------|--------|--------|--------|--------|
| Hb (g/dL) | 7.0 | 7.6 | 10.2 | 9.6 | 7.6 | 8.6 | 10.0 | 10.0 | 12.0-15.0 |
| HCT (%) | 23.0 | 23.5 | 33.1 | 20.0 | 21.8 | 26.8 | 30.8 | \- | 36-46 |
| Platelets (/µL) | 128,000 | 97,000 | 129,000 | 218,000 | 104,000 | 75,000 | 64,000 | 64,000 | 150,000–410,000 |
| PT (seconds) | \- | \- | 12.4 | 40.70 | \- | \- | 17.7 | \- | 11.7–15.3 |
| aPTT (seconds) | \- | \- | \- | \- | \- | \- | 48.90 | \- | 26-40 |
| Fibrinogen (g/L) | \- | \- | \- | \- | \- | 1.4 | \- | \- | 2.00-4.00 |
| D-dimer (µg/mL FEU) | \- | \- | \- | \- | \- | 35.2 | \- | \- | 0-0.55 |
| Total bilirubin (mg/dL) | \- | \- | \- | 2.8 | 1.8 | \- | 1.4 | \- | 1.8-3.5 |
| ALP (IU/L) | \- | \- | \- | 135 | 115 | \- | 108 | \- | 34–104 |
| LDH (IU/L) | \- | 454 | \- | 424 | 357 | \- | 449 | \- | 140–271 |
| BUN (mg/dL) | \- | \- | \- | \- | \- | \- | 24 | \- | 5–23 |
| Serum creatinine (mg/dL) | \- | \- | 0.35 | \- | \- | 0.30 | \- | \- | 0.6–1.2 |

: Relevant abnormal laboratory results throughout the clinical course. {#tbl-2}

POD: Post operative day, Hb: Hemoglobin, HTC: Hematocrit, PT: Prothrombin time, aPTT: Activated partial thromboplastin time, ALP: Alkaline phosphatase, LDH : Lactate dehydrogenase, BUN: Blood Urea Nitrogen.

# Review of literature

We searched MEDLINE, Embase, and Scopus. Only three cases of KTS complicated with KMS in pregnancy have been reported, reflecting the rarity of this condition. KTS was diagnosed prior to pregnancy in two cases, while it was misdiagnosed as acromegaly and only identified during the last trimester in the third [@zhang2019]. All cases had the typical clinical findings of KTS, including multiple varicosities at different sites, hypertrophy, and hemangiomas, with one case also showing port-wine stains [@zhang2019]. Postpartum laboratory findings failed to improve despite treatment suggesting refractory coagulopathy which is consistent with KMS. All cases involved vulval varicosities that necessitated cesarean delivery, with profuse bleeding occurring either during or after the operation and requiring multiple transfusions. All were managed with a multidisciplinary approach and received anticoagulants and transfusions, with two requiring massive transfusion[@Neubert1995; @zhang2019], other lines of treatment included corticosteroids and antifibrinolytics[@Neubert1995; @Kanmani2021]. One patient required postpartum hysterectomy due to life-threatening hemorrhage, along with other severe complications including DIC, sepsis, peritonitis, and hemoperitoneum requiring emergency laparotomy [@zhang2019]. All required prolonged post op hospital admission. None of the neonates showed evidence of KTS. Detailed summary of the three cases is shown in @tbl-3

+------------------------------+---------------------------------------------------------------------------------+------------------------------------------------------------------------------------+-----------------------------------------------------------------------------+------------------------------------------------------------------------------------------+---------------------------------------------------------------+
| Author and year              | Presentation                                                                    | Clinical findings                                                                  | Laboratory findings and KMS diagnosis                                       | Management                                                                               | Maternal and neonatal Outcome                                 |
+==============================+=================================================================================+====================================================================================+=============================================================================+==========================================================================================+===============================================================+
| Neubert, 1995 [@Neubert1995] | 22-year-old known KTS patient, primigravida, 37                                 | Multiple subcutaneous hemangiomas, ipsilateral                                     | DIC Postoperatively with refractory                                         | Uncomplicated cesarean delivery at 39 weeks.                                             | Discharged on post operative day 20. Healthy                  |
|                              | weeks, for genetic counseling and delivery management.                          | thigh hypertrophy and massive right labial varicosities extending along the        | coagulopathy. Thrombocytopenia, elevated PT/PTT and fibrin split products.  | Repeated evacuation of postoperative wound hematoma. ICU transfer, massive               | neonate.                                                      |
|                              |                                                                                 | right vaginal wall.                                                                | Decreased fibrinogen and coagulation factors II, V, and VIII), D-dimer not  | transfusion, Cefotetan, IV heparin and aminocaproic acid.                                |                                                               |
|                              |                                                                                 |                                                                                    | specifically reported. KMS diagnosed postoperatively.                       |                                                                                          |                                                               |
+------------------------------+---------------------------------------------------------------------------------+------------------------------------------------------------------------------------+-----------------------------------------------------------------------------+------------------------------------------------------------------------------------------+---------------------------------------------------------------+
| Kanmani,                     | A 24-year-old known KTS patient, primigravida,                                  | Multiple varicosities, swelling and hypertrophy                                    | Severe thrombocytopenia. Fibrinogen and D-dimer                             | Steroids and platelet transfusion at 16 weeks.                                           | Discharged on post operative day 20. Healthy                  |
|                              | ,29 weeks' gestation, with bleeding gums for two days.                          | of left lower limb. Vulval varicosities.                                           | not reported. KMS diagnosed antenatally.                                    | Daily steroid therapy starting at 29 weeks. Emergency caesarean section at 35            | neonate.                                                      |
| 2021 [@Kanmani2021]          |                                                                                 |                                                                                    |                                                                             | weeks with platelet transfusion. Postoperative anticoagulant and steroid                 |                                                               |
|                              |                                                                                 |                                                                                    |                                                                             | therapy.                                                                                 |                                                               |
+------------------------------+---------------------------------------------------------------------------------+------------------------------------------------------------------------------------+-----------------------------------------------------------------------------+------------------------------------------------------------------------------------------+---------------------------------------------------------------+
| Zhang, 2019 [@zhang2019]     | 26-year-old woman diagnosed with KTS in 3^rd^                                   | Hemodynamically unstable with tender, bulging                                      | KMS diagnosed postoperatively. Labs showed low                              | Caesarean section at 39 weeks for large                                                  | Hysterectomy due to uncontrolled hemorrhage.                  |
|                              | trimester, presented with sudden heavy vaginal bleeding 10 days after caesarean | lower abdomen, subcutaneous ecchymoses, and palpable incisional mass. Multiple     | hemoglobin and hematocrit with thrombocytopenia ,prolonged PT and APTT. Low | vulvovaginal varicosities. All measures failed to control postpartum bleeding. Emergency | Discharged after 42 days of hospitalization. Healthy neonate. |
|                              | delivery.                                                                       | hemangiomas, varicosities, and port-wine stains over left buttock and entire       | Fibrinogen and elevated P-FDP, unmeasurable D-dimer.                        | hysterectomy, followed by laparotomy for hemoperitoneum with pelvic packing,             |                                                               |
|                              |                                                                                 | left lower limb, with massive limb hypertrophy and large left labial varicosities. |                                                                             | bilateral internal iliac artery embolization, and wound dehiscence closure.              |                                                               |
|                              |                                                                                 |                                                                                    |                                                                             | Coagulopathy managed with LMWH and warfarin.                                             |                                                               |
+------------------------------+---------------------------------------------------------------------------------+------------------------------------------------------------------------------------+-----------------------------------------------------------------------------+------------------------------------------------------------------------------------------+---------------------------------------------------------------+

: {#tbl-3}

# Discussion

The occurrence of KTS complicated by KMS during pregnancy is extremely rare, and, to our knowledge, only three cases have been reported. [@Neubert1995; @Kanmani2021; @zhang2019]

Klippel-Trenaunay Syndrome (KTS), also referred to as capillary-lymphatic-venous malformation (CLVM), is characterized by capillary malformations, soft tissue or bony hypertrophy, and varicose veins or venous malformations. The presence of at least two of these features suggests the diagnosis, which is supported by imaging. Magnetic resonance imaging, Color Doppler studies, and pelviabdominal ultrasounds may all be used to visualize vascular malformations associated with KTS.[@horbach2017]

Its hallmark features predominantly affect one lower limb (85%) causing a discrepancy in limb length, although bilateral involvement may occur in a minority of cases (12.5%). However, it is a generalized disorder and can involve multiple body regions including the pelvis, abdomen, head and neck, as well as back, pelvis, and bladder as in our case. Capillary malformations are the most common presentation (98%), followed by varicosities or venous malformations (72%), and limb hypertrophy (67%) [@Jacob1998].

Morbidity in KTS primarily arises from an increased risk of venous insufficiency, thromboembolism, and hemorrhage. Pregnancy may further aggravate these risks, although evidence regarding pregnancy outcomes and optimal management remains limited. A cross-sectional study of sixty adult women with KTS reported increased risks of pregnancy-associated deep vein thrombosis, pulmonary embolism, and severe postpartum hemorrhage compared with the general population, with nearly half the patients also experiencing exacerbation of KTS-related symptoms[@silvacorreia2024]. In contrast, another study comparing pregnant women with KTS versus nulligravid women with KTS found no difference in bleeding or thromboembolic risk, although a limitation was the possibility of women with more severe KTS being discouraged from pregnancy [@Marvin2019].

Fetal complications, including intrauterine growth restriction (IUGR), were reported in a few cases, including our case. However, no significant fetal effects were reported in the majority of patients with KTS, indicating that its impact on fetal development is generally limited.[@Akay2025]

Patients may present with a wide variety of manifestations either primary or due to complications such as pain, bleeding, cellulitis, massive vaginal bleeding, visceral bleeding, and bleeding gums, and other vascular complications such as severe hematuria and hematochezia (fewer than 5%). Our case presented with clinically significant hematuria. Other less common but serious manifestations include deep vein thrombosis (5.8%), pulmonary embolism (2.3%), severe PPH (11%), and potential preeclampsia. [@Akay2025; @Chang2025]

Kasabach-Merritt Syndrome (KMS), a rare but life-threatening complication, is characterized by thrombocytopenia, microangiopathic hemolytic anemia, and consumptive coagulopathy in the presence of a vascular tumor [@Mahajan2017]. Patients commonly present with persistent bleeding and thrombocytopenia refractory to blood products. Our patient developed post-op hematoma and hemoperitoneum which was managed conservatively with success. Specific therapy was initiated once Kasabach-Merritt syndrome was suspected and the patient eventually made a complete recovery. The prompt recognition and initiation of therapy are critical to reduce mortality in KMS. Delayed recognition was associated with more complicated clinical courses, as in the KTS patient at 39 weeks who was not previously diagnosed with KTS, and did not receive LMWH, losing 1500 mL of blood of post-op and 4500mL of blood through vaginal bleeding on day 10 postpartum, necessitating a hysterectomy and abdominal gauze packing.[@zhang2019]

Diagnosis of KMS is confirmed by lab findings of thrombocytopenia, hypofibrinogenemia, elevated D-dimer, and prolonged coagulation times. The absence of thrombocytopenia may indicate refractory coagulopathy rather than KMS, although atypical presentations should be suspected in presence of hemangiomas.[@Chang2025]

The management of KTS becomes more complex when complicated by Kasabach Merritt syndrome (KMS). Imaging studies are crucial for assessing the extent of vascular malformations near the spinal cord and pelvic structures, with MRI being the preferred imaging modality for accurately evaluating lesions size, extent, and anatomical involvement which is critical for planning the anesthesia and delivery type. Doppler ultrasound is effective for diagnosing venous malformations. Regular maternal and fetal assessment is essential due to risk of placental involvement [@Howlett1994; @Asghar2020]. Our patient underwent first-trimester ultrasound and MRI at 30 weeks. MRI demonstrated extensive venous malformations involving the pelvic, perivesical, perineal, gluteal, thigh, and anterior abdominal regions. Ultrasound revealed hepatosplenomegaly, soft tissue lesions in the urinary bladder, bilateral refluxing parametrial venous channels, and no evidence of deep vein thrombosis.

Deciding the mode of delivery in a pregnant woman with KTS requires a multidisciplinary team (MDT). In most reported cases, cesarean section was opted for due to the presence of vulval varicosities.[@Keepanasseril2017] In our case, emergency cesarean section under general anesthesia was recommended by an MDT involving obstetrics, hematology, anesthesia, and neonatology due to both fetal and maternal risks. Vertical midline abdominal incision revealed significant varicosities in the anterior abdominal wall, over the lower uterine segment, and in the interface between the uterus and the bladder. Comprehensive preparations were made before and after delivery, including the administration of tranexamic acid and LMWH.

Prophylactic anticoagulation with LMWH should be considered during pregnancy period given the elevated risk of VTE [@marvin2019], with regular coagulopathy monitoring and Imaging. Postpartum management may involve anticoagulation, platelet transfusion, cryoprecipitate, fresh frozen plasma and antifibrinolytic agents such as TXA. Postpartum follow up is essential as KMS can develop or worsen after delivery and they may require large volumes of blood products to manage the ongoing coagulopathy, but typically remain refractory, showing minimal to no improvement. [@silvacorreia2024]

# Conclusion

Pregnancy in women with Klippel–Trenaunay syndrome complicated by Kasabach–Merritt syndrome is extremely rare and posing significant diagnostic challenges. Early suspicion and diagnosis with intensive antenatal surveillance and multidisciplinary management are crucial to navigate the complex balance between thrombosis and bleeding and to optimize maternal and perinatal outcomes in such high risk cases.

# Abbreviation

Klippel-Trenaunay syndrome (KTS)

Kasabach Meritt Syndrome (KMS)

Magnetic resonance imaging (MRI)

Ultrasonography (US)

Transvaginal ultrasound (TVUS)

Intensive care unit (ICU)

Low-molecular-weight heparin (LMWH)

Lactate dehydrogenase (LDH)

Blood Urea Nitrogen (BUN)

Prothrombin time (PT)

Partial Thromboplastin Time (PTT)

Complete blood picture (CBC)

Disseminated Intravascular Coagulation (DIC)

Multidisciplinary team (MDT)

# Declarations

## Ethics approval and consent to participate

Not applicable.

## Consent for publication

A written consent for publication has been obtained from the patient.

## Availability of data and materials

The data and materials supporting the conclusions of this article are available as a supplementary materials.

## Competing interests

The authors declare that they have no competing interests.

## Funding

This research received no specific grant from any funding agency in the public, commercial or not-for-profit sectors.

## Authors' contributions

SIA, ME, AFN contributed to writing the first draft of the manuscript. All the authors revised the manuscript critically for important intellectual content. All authors approved the final version of the manuscript.

## Acknowledgements

We sincerely thank the healthcare providers at Ain Shams University Hospital of Obstetrics and Gynecology for their dedication and commitment to patient care in the operating room. We deeply appreciate their contributions and the valuable role they play in ensuring high-quality surgical care.

# References
